# Generated by Django 2.0.6 on 2018-06-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=5500)),
                ('publication_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
